version: '3'
services:
  
  kubectl:
    image: bitnami/kubectl:latest
    volumes: 
      - ./kubeconfig.yaml:/.kube/config
      - ./example:/example
    depends_on: 
      - server

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server
    tmpfs:
      - /run
      - /var/run
    privileged: true
    env_file: .env
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - .:/output
    ports:
      - 6443:6443

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
      - /run
      - /var/run
    privileged: true
    env_file: .env
    environment:
      - K3S_URL=https://server:6443
    depends_on: 
      - server

volumes:
  k3s-server: 